#!/bin/bash

app_id=$BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_APP_ID
description="${BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_DESCRIPTION:-${BUILDKITE_MESSAGE:-}}"
user="${BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_USER:-${BUILDKITE_BUILD_CREATOR_EMAIL:-}}"
revision="${BUILDKITE_BUILD_NUMBER:-}"
api_key="${BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_API_KEY:-${NEW_RELIC_API_KEY:-}}"

echo "--- :newrelic: Creating deploment marker for $app_id"

if [ -z $api_key ]; then
  ssm_param_name=${BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_API_KEY_SSM_PARAM_NAME:-"NEWRELIC_API_KEY"}
  api_key=$(aws ssm get-parameter --with-decryption --name "$ssm_param_name" --query=Parameter.Value --output=text)
else
  api_key=$BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_API_KEY
fi

curl -X POST "https://api.newrelic.com/v2/applications/${app_id}/deployments.json" \
   -H "X-Api-Key:${api_key}" -i \
   -H "Content-Type: application/json" \
   -d \
  '{
    "deployment": {
      "revision": "'"${revision}"'",
      "description": "'"${description}"'",
      "user": "'"${user}"'"
    } 
  }' 


